import { Router } from "express";

import { aiRouter } from "./modules/ai/ai.routes.js";
import { feeAssignmentsRouter } from "./modules/feeAssignments/feeAssignments.routes.js";
import { productCategoriesRouter } from "./modules/productCategories/productCategories.routes.js";
import { uploadsRouter } from "./modules/uploads/uploads.routes.js";
import { authRouter } from "./modules/auth/auth.routes.js";
import { guardiansRouter } from "./modules/guardians/guardians.routes.js";
import { guardianPortalRouter } from "./modules/guardians/guardianPortal.routes.js";
import { employeesRouter } from "./modules/employees/employees.routes.js";
import { payrollRouter } from "./modules/payroll/payroll.routes.js";
import { cashDrawersRouter } from "./modules/cashDrawers/cashDrawers.routes.js";
import { staffRouter } from "./modules/staff/staff.routes.js";
import { customersRouter } from "./modules/customers/customers.routes.js";
import { bulkImportRouter } from "./modules/customers/bulkImport.routes.js";
import { demoRouter } from "./modules/demo/demo.routes.js";
import { studentAppRouter } from "./modules/integrations/studentApp.routes.js";
import { inventoryRouter } from "./modules/inventory/inventory.routes.js";
import { inventoryAIRouter } from "./modules/inventory/inventoryAI.routes.js";
import { organizationsRouter } from "./modules/organizations/organizations.routes.js";
import { ordersRouter } from "./modules/orders/orders.routes.js";
import { productsRouter } from "./modules/products/products.routes.js";
import { productImportRouter } from "./modules/products/productImport.routes.js";
import { reportsRouter } from "./modules/reports/reports.routes.js";
import { storesRouter } from "./modules/stores/stores.routes.js";
import { studentCredentialsRouter } from "./modules/studentCredentials/studentCredentials.routes.js";
import { walletsRouter } from "./modules/wallets/wallets.routes.js";
import { transactionsRouter } from "./modules/transactions/transactions.routes.js";
import { authenticateRequest } from "./shared/auth/auth.js";
import { requireFeature } from "./shared/auth/featureGate.js";

export const apiRouter = Router();

apiRouter.use("/auth", authRouter);
apiRouter.use("/guardian-portal", guardianPortalRouter); // parent-facing, own auth
apiRouter.use(authenticateRequest);

apiRouter.use("/organizations", organizationsRouter);
apiRouter.use("/product-categories", productCategoriesRouter);
apiRouter.use("/fee-assignments", requireFeature("fee_assignments"), feeAssignmentsRouter);
apiRouter.use("/cash-drawers", cashDrawersRouter);
apiRouter.use("/stores", storesRouter);
apiRouter.use("/products/import", productImportRouter);
apiRouter.use("/products", productsRouter);
apiRouter.use("/customers/bulk-import", bulkImportRouter);
apiRouter.use("/customers", customersRouter);
apiRouter.use("/wallets", walletsRouter);
apiRouter.use("/orders", ordersRouter);
apiRouter.use("/reports", reportsRouter);
apiRouter.use("/student-credentials", studentCredentialsRouter);
apiRouter.use("/demo", demoRouter);
apiRouter.use("/integrations/student-app", requireFeature("student_integration"), studentAppRouter);
apiRouter.use("/inventory/ai", inventoryAIRouter);
apiRouter.use("/inventory", inventoryRouter);
apiRouter.use("/staff", staffRouter);
apiRouter.use("/ai", aiRouter);
apiRouter.use("/employees", requireFeature("payroll"), employeesRouter);
apiRouter.use("/payroll", requireFeature("payroll"), payrollRouter);
apiRouter.use("/guardians", requireFeature("guardians"), guardiansRouter);
apiRouter.use("/uploads", uploadsRouter);
apiRouter.use("/transactions", transactionsRouter);
